version: '3'
services:
  front:
    image: nginx:latest
    volumes:
      - ./front/docker/xm_front_nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./front:/var/app:cached
    ports:
      - "8881:80"
    command: /bin/bash -c "exec nginx -g 'daemon off;'"

  php:
    build:
      context: ./
      dockerfile: ./back/docker/php/Dockerfile
    volumes:
      - ./back:/var/app:cached
    command:
      /bin/bash -c "exec php-fpm"

  nginx:
    image: nginx:latest
    volumes:
      - ./back/docker/nginx/xm_back_nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./back:/var/app:cached
    ports:
      - "8882:80"
    environment:
      - APP_ENV=dev
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    depends_on:
      - php

  redis:
    image: redis:latest
    ports:
      - "6399:6379"
    depends_on:
      - php